/**
 * EnhancedPDFGenerator.swift
 * Professional PDF Generation with Branding
 *
 * Features:
 * - Custom branded templates
 * - Header/footer with logo
 * - Multiple page layouts
 * - Signature certificates
 * - QR code generation for verification
 */

import Foundation
import PDFKit
import UIKit
import CoreImage.CIFilterBuiltins

class EnhancedPDFGenerator {
    
    // MARK: - PDF Configuration
    
    struct PDFConfig {
        var companyName: String
        var companyLogo: UIImage?
        var headerColor: UIColor
        var accentColor: UIColor
        var footerText: String
        var includeQRCode: Bool
        var includeWatermark: Bool
        var watermarkText: String?
        var pageSize: CGRect
        
        static var standard: PDFConfig {
            PDFConfig(
                companyName: "DigitalForms",
                companyLogo: nil,
                headerColor: .systemBlue,
                accentColor: .systemBlue,
                footerText: "Generated by DigitalForms App",
                includeQRCode: true,
                includeWatermark: false,
                watermarkText: nil,
                pageSize: CGRect(x: 0, y: 0, width: 612, height: 792) // US Letter
            )
        }
    }
    
    // MARK: - Generate PDF
    
    static func generateBrandedPDF(
        form: LocalForm,
        signatures: [LegalSignature] = [],
        config: PDFConfig = .standard
    ) -> Data? {
        
        let pdfMetadata = [
            kCGPDFContextTitle: form.title ?? "Form",
            kCGPDFContextCreator: "DigitalForms App",
            kCGPDFContextAuthor: config.companyName
        ]
        
        let format = UIGraphicsPDFRendererFormat()
        format.documentInfo = pdfMetadata as [String: Any]
        
        let renderer = UIGraphicsPDFRenderer(bounds: config.pageSize, format: format)
        
        let data = renderer.pdfData { context in
            var yPosition: CGFloat = 0
            
            // Page 1: Form Content
            context.beginPage()
            yPosition = drawHeader(in: context, config: config, pageNumber: 1)
            yPosition = drawFormTitle(form: form, yPosition: yPosition, context: context, config: config)
            yPosition = drawFormMetadata(form: form, yPosition: yPosition, context: context, config: config)
            yPosition = drawFormFields(form: form, yPosition: yPosition, context: context, config: config)
            drawFooter(in: context, config: config, pageNumber: 1, totalPages: signatures.isEmpty ? 1 : 2)
            
            // Page 2: Signatures (if present)
            if !signatures.isEmpty {
                context.beginPage()
                yPosition = drawHeader(in: context, config: config, pageNumber: 2)
                yPosition = drawSignatures(signatures: signatures, yPosition: yPosition, context: context, config: config)
                drawFooter(in: context, config: config, pageNumber: 2, totalPages: 2)
            }
            
            // Watermark (if enabled)
            if config.includeWatermark, let watermarkText = config.watermarkText {
                drawWatermark(text: watermarkText, in: context, config: config)
            }
        }
        
        return data
    }
    
    // MARK: - Drawing Methods
    
    private static func drawHeader(in context: UIGraphicsPDFRendererContext, config: PDFConfig, pageNumber: Int) -> CGFloat {
        let headerHeight: CGFloat = 80
        let headerRect = CGRect(x: 0, y: 0, width: config.pageSize.width, height: headerHeight)
        
        // Header background
        context.cgContext.setFillColor(config.headerColor.cgColor)
        context.cgContext.fill(headerRect)
        
        // Company logo
        if let logo = config.companyLogo {
            let logoSize = CGSize(width: 50, height: 50)
            let logoRect = CGRect(
                x: 40,
                y: (headerHeight - logoSize.height) / 2,
                width: logoSize.width,
                height: logoSize.height
            )
            logo.draw(in: logoRect)
        }
        
        // Company name
        let textAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 24),
            .foregroundColor: UIColor.white
        ]
        
        let logoOffset: CGFloat = config.companyLogo != nil ? 100 : 40
        let textRect = CGRect(x: logoOffset, y: 30, width: 400, height: 40)
        (config.companyName as NSString).draw(in: textRect, withAttributes: textAttributes)
        
        return headerHeight + 20
    }
    
    private static func drawFormTitle(form: LocalForm, yPosition: CGFloat, context: UIGraphicsPDFRendererContext, config: PDFConfig) -> CGFloat {
        let titleAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 20),
            .foregroundColor: UIColor.black
        ]
        
        let title = form.title ?? "Untitled Form"
        let titleRect = CGRect(x: 40, y: yPosition, width: config.pageSize.width - 80, height: 30)
        (title as NSString).draw(in: titleRect, withAttributes: titleAttributes)
        
        return yPosition + 40
    }
    
    private static func drawFormMetadata(form: LocalForm, yPosition: CGFloat, context: UIGraphicsPDFRendererContext, config: PDFConfig) -> CGFloat {
        let metadataAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12),
            .foregroundColor: UIColor.darkGray
        ]
        
        var y = yPosition
        
        // Form ID
        let formId = "Form ID: \(form.id?.uuidString.prefix(8) ?? "N/A")"
        (formId as NSString).draw(at: CGPoint(x: 40, y: y), withAttributes: metadataAttributes)
        y += 20
        
        // Status
        let status = "Status: \(form.statusEnum.displayName)"
        (status as NSString).draw(at: CGPoint(x: 40, y: y), withAttributes: metadataAttributes)
        y += 20
        
        // Created date
        if let createdAt = form.createdAt {
            let dateFormatter = DateFormatter()
            dateFormatter.dateStyle = .medium
            dateFormatter.timeStyle = .short
            let created = "Created: \(dateFormatter.string(from: createdAt))"
            (created as NSString).draw(at: CGPoint(x: 40, y: y), withAttributes: metadataAttributes)
            y += 20
        }
        
        // QR Code for verification
        if config.includeQRCode, let formId = form.id {
            let qrCode = generateQRCode(string: formId.uuidString)
            let qrRect = CGRect(x: config.pageSize.width - 140, y: yPosition, width: 100, height: 100)
            qrCode?.draw(in: qrRect)
        }
        
        return y + 20
    }
    
    private static func drawFormFields(form: LocalForm, yPosition: CGFloat, context: UIGraphicsPDFRendererContext, config: PDFConfig) -> CGFloat {
        let labelAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 14),
            .foregroundColor: UIColor.black
        ]
        
        let valueAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 13),
            .foregroundColor: UIColor.darkGray
        ]
        
        let sectionAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 16),
            .foregroundColor: config.accentColor
        ]
        
        var y = yPosition
        let maxWidth = config.pageSize.width - 80
        
        for field in form.fields.sorted(by: { $0.order < $1.order }) {
            // Check if we need a new page
            if y > config.pageSize.height - 100 {
                // Would need to handle page breaks here
                break
            }
            
            let fieldType = FieldType(rawValue: field.type) ?? .text
            
            if fieldType == .section {
                // Section header
                y += 15
                (field.label as NSString).draw(at: CGPoint(x: 40, y: y), withAttributes: sectionAttributes)
                y += 30
                
                // Underline
                context.cgContext.setStrokeColor(config.accentColor.cgColor)
                context.cgContext.setLineWidth(2)
                context.cgContext.move(to: CGPoint(x: 40, y: y))
                context.cgContext.addLine(to: CGPoint(x: config.pageSize.width - 40, y: y))
                context.cgContext.strokePath()
                y += 10
            } else {
                // Field label
                var labelText = field.label
                if field.required {
                    labelText += " *"
                }
                (labelText as NSString).draw(at: CGPoint(x: 40, y: y), withAttributes: labelAttributes)
                y += 20
                
                // Field value
                let value = field.value ?? "(No value)"
                let valueRect = CGRect(x: 40, y: y, width: maxWidth, height: 60)
                (value as NSString).draw(in: valueRect, withAttributes: valueAttributes)
                y += 35
                
                // Separator line
                context.cgContext.setStrokeColor(UIColor.lightGray.cgColor)
                context.cgContext.setLineWidth(0.5)
                context.cgContext.move(to: CGPoint(x: 40, y: y))
                context.cgContext.addLine(to: CGPoint(x: config.pageSize.width - 40, y: y))
                context.cgContext.strokePath()
                y += 15
            }
        }
        
        return y
    }
    
    private static func drawSignatures(signatures: [LegalSignature], yPosition: CGFloat, context: UIGraphicsPDFRendererContext, config: PDFConfig) -> CGFloat {
        let titleAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 18),
            .foregroundColor: config.accentColor
        ]
        
        var y = yPosition
        
        ("Signatures" as NSString).draw(at: CGPoint(x: 40, y: y), withAttributes: titleAttributes)
        y += 40
        
        for signature in signatures {
            y = drawSignatureCertificate(signature: signature, yPosition: y, context: context, config: config)
        }
        
        return y
    }
    
    private static func drawSignatureCertificate(signature: LegalSignature, yPosition: CGFloat, context: UIGraphicsPDFRendererContext, config: PDFConfig) -> CGFloat {
        let boxRect = CGRect(x: 40, y: yPosition, width: config.pageSize.width - 80, height: 200)
        
        // Box background
        context.cgContext.setFillColor(UIColor.systemGray6.cgColor)
        context.cgContext.fill(boxRect)
        
        // Box border
        context.cgContext.setStrokeColor(config.accentColor.cgColor)
        context.cgContext.setLineWidth(2)
        context.cgContext.stroke(boxRect)
        
        let infoAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12),
            .foregroundColor: UIColor.black
        ]
        
        var y = yPosition + 15
        
        // Signer name
        let name = "Signer: \(signature.signerName)"
        (name as NSString).draw(at: CGPoint(x: 50, y: y), withAttributes: infoAttributes)
        y += 20
        
        // Email
        let email = "Email: \(signature.signerEmail)"
        (email as NSString).draw(at: CGPoint(x: 50, y: y), withAttributes: infoAttributes)
        y += 20
        
        // Signed date
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .long
        dateFormatter.timeStyle = .medium
        let signed = "Signed: \(dateFormatter.string(from: signature.signedAt))"
        (signed as NSString).draw(at: CGPoint(x: 50, y: y), withAttributes: infoAttributes)
        y += 20
        
        // Document hash
        let hash = "Hash: \(signature.documentHash.prefix(32))..."
        (hash as NSString).draw(at: CGPoint(x: 50, y: y), withAttributes: infoAttributes)
        y += 20
        
        // Signature image (if available)
        if let signatureData = Data(base64Encoded: signature.signatureData.replacingOccurrences(of: "data:image/png;base64,", with: "")),
           let signatureImage = UIImage(data: signatureData) {
            let sigRect = CGRect(x: 50, y: y, width: 200, height: 60)
            signatureImage.draw(in: sigRect)
        }
        
        return yPosition + 220
    }
    
    private static func drawFooter(in context: UIGraphicsPDFRendererContext, config: PDFConfig, pageNumber: Int, totalPages: Int) {
        let footerY = config.pageSize.height - 50
        
        let footerAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 10),
            .foregroundColor: UIColor.gray
        ]
        
        // Footer text
        (config.footerText as NSString).draw(at: CGPoint(x: 40, y: footerY), withAttributes: footerAttributes)
        
        // Page number
        let pageText = "Page \(pageNumber) of \(totalPages)"
        let pageTextSize = (pageText as NSString).size(withAttributes: footerAttributes)
        (pageText as NSString).draw(
            at: CGPoint(x: config.pageSize.width - pageTextSize.width - 40, y: footerY),
            withAttributes: footerAttributes
        )
    }
    
    private static func drawWatermark(text: String, in context: UIGraphicsPDFRendererContext, config: PDFConfig) {
        let watermarkAttributes: [NSAttributedString.Key: Any] = [
            .font: UIFont.boldSystemFont(ofSize: 60),
            .foregroundColor: UIColor.gray.withAlphaComponent(0.1)
        ]
        
        context.cgContext.saveGState()
        context.cgContext.translateBy(x: config.pageSize.width / 2, y: config.pageSize.height / 2)
        context.cgContext.rotate(by: -.pi / 4)
        
        let textSize = (text as NSString).size(withAttributes: watermarkAttributes)
        (text as NSString).draw(
            at: CGPoint(x: -textSize.width / 2, y: -textSize.height / 2),
            withAttributes: watermarkAttributes
        )
        
        context.cgContext.restoreGState()
    }
    
    // MARK: - QR Code Generation
    
    private static func generateQRCode(string: String) -> UIImage? {
        let context = CIContext()
        let filter = CIFilter.qrCodeGenerator()
        
        filter.message = Data(string.utf8)
        filter.correctionLevel = "M"
        
        guard let outputImage = filter.outputImage else { return nil }
        
        let scaleX = 100 / outputImage.extent.size.width
        let scaleY = 100 / outputImage.extent.size.height
        let transformedImage = outputImage.transformed(by: CGAffineTransform(scaleX: scaleX, y: scaleY))
        
        guard let cgImage = context.createCGImage(transformedImage, from: transformedImage.extent) else {
            return nil
        }
        
        return UIImage(cgImage: cgImage)
    }
}
